### PR TITLE
Final Version of the Mint Sign Up Page Clone

### PR DESCRIPTION
**Pull request by SpaYco**
## Displaying and Inputting Data: Mint Sign-Up Clone

- Added a Sign-In Button
- Added a Sign-Up Form
- Added a TOS text

[Live Version](https://raw.githack.com/Spayco/mint-clone/featureOfMintProject/index.html)

P.S: I did most of the page with my partner but then he quit and I finished some final touches on my own (with permission from the success team).

### CODE REVIEW

**Review by imhta — CHANGES_REQUESTED** [review]
# Changes required 🛑 

### Hello  @Spayco @supersebek  , 👋 You have done a great job in this project 👏 

* [ ] It has an `<input>` of type `tel` and a label `Phone` ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/html_forms/form_and_input_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59524927/))

----
### Don't forgot to request for another code review
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__
_If you have any queries, feel free to ping me on slack_

**Review by imhta — APPROVED** [review]
# Project approved 🎉 

### Hello  @Spayco @supersebek  , 👋 You have done a great job in this project 👏 
> [Optional] Completed your basic requirements, If you wish, can do fine-tuning in the project UI to be pixel perfect clone



----
### Happy coding 😄 
----
**Pon Muthu Selvam N**
__nponmuthuselvam@gmail.com__

**Comment by imhta** [comment]
Before merging this branch, Kindly install stickler to this repo, and fix errors if it shows. 

> Meanwhile don't forget to install stickler in next project too

**Comment by SpaYco** [comment]
> Before merging this branch, Kindly install stickler to this repo, and fix errors if it shows.
> 
> > Meanwhile don't forget to install stickler in next project too

I did check locally since for some reason it's not working here

**Pull request merged**
